# Welcome to numpy tutorial 

In [2]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 32,  7]])

# Array Creation : Conversion from python structures

In [10]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.size

9

In [15]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [16]:
listarray[0,1]

2

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
lspace = np.linspace(1,4,4)

In [32]:
lspace

array([1., 2., 3., 4.])

In [33]:
emp = np.empty((4,6))

In [34]:
emp

array([[-2.00000000e+000, -2.00000000e+000,  1.77863633e-322,
         0.00000000e+000,  0.00000000e+000,  4.17201348e-309],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000, -2.00000000e+000, -2.00000000e+000]])

In [37]:
emp_like = np.empty_like(lspace)

In [38]:
emp_like

array([1., 2., 3., 4.])

In [39]:
ide = np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [41]:
ide.shape

(45, 45)

In [42]:
arr = np.arange(99)

In [43]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.shape

(99,)

## Axis in NumPy

In [46]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [47]:
ar = np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
ar.flat

In [53]:
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
1
0


In [54]:
ar.ndim

2

In [55]:
ar.size

9

In [56]:
one = np.array([1,3,4,634,2])

In [57]:
one.argmax()

3

In [58]:
one.argmin()

0

In [59]:
one.argsort()

array([0, 4, 1, 2, 3])

# Accessing or changing specific rows


In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a[1,5]

13

In [6]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a[:,2]

array([ 3, 10])

In [8]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [9]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [10]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# Get specific element (work outside in)
b[0,1,1]

4

In [12]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Linear Algebra

In [14]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [15]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [16]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.min(stats)

1

In [18]:
np.max(stats, axis=1)

array([3, 6])

In [19]:
np.sum(stats, axis=0)


array([5, 7, 9])

# Reorganizing Arrays

In [22]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])